name: 打包EXE发布

on:
  workflow_dispatch:
    inputs:
      #java_version:
      #  description: "The version of Java to use for jpackage"
      #  required: true
      app_version:
        description: "应用版本，如1.0.1"
        required: true
      release_notes:
        description: "Release描述"
        required: false

jobs:
  dmg_build:
    runs-on: windows-latest # 因为要生成.dmg格式，需要在MacOS环境下运行

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.1'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Download JavaFX SDK
        run: |
          Invoke-WebRequest -Uri https://download2.gluonhq.com/openjfx/23.0.1/openjfx-23.0.1_osx-x64_bin-sdk.zip -OutFile javafx-sdk.zip
          Expand-Archive -Path javafx-sdk.zip -DestinationPath javafx-sdk
          dir
          
      - name: Install Unzip Tool (if not already installed)
        run: |
          choco install unzip -y
          dir
      - name: Extract JavaFX SDK
        run: |
          unzip  javafx-sdk.zip
          dir
          $env:JAVAFX_SDK_PATH = "$((Get-Location).Path)\javafx-sdk\lib"
          $env:JAVAFX_ADD_MODULES = "javafx.controls,javafx.fxml,javafx.graphics"
          echo $env:JAVAFX_SDK_PATH
          echo $env:JAVAFX_ADD_MODULES

      - name: Package with EXE
        run: |
          jpackage --input target   --name "Tooool"  --main-jar Tooool-1.0-SNAPSHOT-jar-with-dependencies.jar   --main-class tech.xueyao.tooool.ToooolApplication --type exe  --dest target  --java-options "--module-path $env:JAVAFX_MODULE_PATH --add-modules $env:JAVAFX_ADD_MODULES " --icon src/main/resources/tech/xueyao/tooool/img/app-win.ico     --app-version ${{ inputs.app_version }}

          cd target   
          dir
      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          #tag_name: ${{ github.ref }}
          #name: Release ${{ github.ref }}
          tag_name: v${{ inputs.app_version }}
          name: Release v${{ inputs.app_version }}
          body: ${{ inputs.release_notes }}
          draft: false
          prerelease: false
          files: |
              /a/Tooool/Tooool/target/Tooool-${{ inputs.app_version }}.exe
