# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Mac Client

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-13

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.1'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: DMG file
          path: target/installer/*.dmg
      - name: Upload PKG
        uses: actions/upload-artifact@v4
        with:
          name: PKG file
          path: target/installer/*.pkg