# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Windows Client

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.1'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install
      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: MSI file
          path: target/installer/*.msi