name: 打包DMG并发布

on:
  push:
  #  tags:
  #    - "*"   

jobs:
  dmg_build:
    runs-on: windows-latest # 因为要生成.dmg格式，需要在MacOS环境下运行

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.1'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Download JavaFX SDK
        run: |
          Invoke-WebRequest -Uri https://download2.gluonhq.com/openjfx/23.0.1/openjfx-23.0.1_osx-x64_bin-sdk.zip -OutFile javafx-sdk.zip
          Expand-Archive -Path javafx-sdk.zip -DestinationPath javafx-sdk
          dir
          
      - name: Install Unzip Tool (if not already installed)
        run: |
          choco install unzip -y
          dir
      - name: Extract JavaFX SDK
        run: |
          unzip  javafx-sdk.zip
          dir
          $env:JAVAFX_SDK_PATH = "$((Get-Location).Path)\javafx-sdk\lib"
          $env:JAVAFX_ADD_MODULES = "javafx.controls,javafx.fxml,javafx.graphics"
          
      - name: Package with EXE
        run: |
          jpackage --input target   --name "Tooool"  --main-jar Tooool-1.0-SNAPSHOT-jar-with-dependencies.jar   --main-class tech.xueyao.tooool.ToooolApplication --type exe  --dest target  --java-options "--module-path $env:JAVAFX_MODULE_PATH --add-modules $env:JAVAFX_ADD_MODULES " --icon src/main/resources/tech/xueyao/tooool/img/app-win.png
          cd target   
          dir
      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          #tag_name: ${{ github.ref }}
          #name: Release ${{ github.ref }}
          tag_name: v0.1.0
          name: Release v0.1.0
          body: |
            这是一个新的发布
          draft: false
          prerelease: false
          files: |
              Tooool-1.0.exe
