name: Build and Package Java Application

on:
  push:
   tags:
      - "*" # 可以根据你的实际需求修改触发的分支，这里以main分支为例


jobs:
  build_and_package:
    runs-on: macos-latest # 因为要生成.dmg格式，需要在MacOS环境下运行

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.1'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Download JavaFX SDK
        run: |
          wget https://download2.gluonhq.com/openjfx/23.0.1/openjfx-23.0.1_osx-x64_bin-sdk.zip -P /tmp/

      - name: Extract JavaFX SDK
        run: |
          tar -zxvf /tmp/openjfx-23.0.1_osx-x64_bin-sdk.zip -C /tmp/
          export JAVAFX_SDK_PATH="/tmp/javafx-sdk-23.0.1/lib"
      - name: Package with JPackage
        run: |
          jpackage \
            --input target/ \
            --name "超级小工具" \
            --main-jar Tooool-1.0-SNAPSHOT-jar-with-dependencies.jar \
            --main-class tech.xueyao.tooool.ToooolApplication \
            --type dmg \
            --dest target/ \
            --java-options "--module-path $JAVAFX_SDK_PATH$JAVAFX_SDK_PATH \
            --add-modules javafx.controls,javafx.fxml" \
            --icon src/main/resources/tech/xueyao/tooool/img/app-mac.icns
      #- name: Create Release
      #  uses: actions/create-release@v1
      #  env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: refs/tags/v0.1.2
      #    release_name: "Release v0.1"
      #    draft: false
      #    prerelease: false
      - name: Upload DMG to Release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.dmg
     # - name: Upload DMG to Release
     #   uses: alexellis/upload-assets@0.4.1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       # with:
       #     asset_paths: '["./bin/超级小工具*"]'
            #upload_url: ${{ steps.create_release.outputs.upload_url }}
            #asset_path: target/超级小工具-1.0.dmg
            #asset_name: 超级小工具-1.0.dmg
       #     asset_content_type: application/octet-stream
