name: Build and Package JavaFX to EXE

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvn build
      - name: Package to EXE
        uses: wix-toolset/msbuild-action@v1
        with:
          project-file: 'https://github.com/flowstone/Tooool'
          configuration: 'Release'
          msbuild-arguments: '/p:OutputPath=output-dir'
