name: Build and Package JavaFX to DMG

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw build
      - name: Package to DMG
        uses: electron-userland/electron-builder-action@v1
        with:
          config: |
            {
              "mac": {
                "category": "public.app-category.utilities",
                "target": ["dmg"]
              }
            }
